language: python

python:
  - "3.6.3"

services:
  - postgresql

addons:
  chrome: stable

env:
  - DJANGO_SETTINGS_MODULE=mysite.settings.travisci

before_install:
  - wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
  - mkdir chromedriver
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:$PWD/chromedriver
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 &

install:
  - pip install -r requirements.txt

before_script:
  - createdb -E UTF-8 blog

script:
  - python manage.py test --noinput
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py radish features/
